const plan = {
  monday: {
    1: "PAI",
    2: "PAI",
    3: "j. Polski",
    4: "j. Polski",
    5: "Matematyka",
    6: "Matematyka",
    7: "Grafika komputerowa",
    8: "Grafika komputerowa",
  },
  tuesday: {
    1: "PAI",
    2: "PAI",
    3: "j. Polski",
    4: "j. Polski",
    5: "Matematyka",
    6: "Matematyka",
    7: "Grafika komputerowa",
    8: "Grafika komputerowa",
  },
  wednesday: {
    1: "PAI",
    2: "PAI",
    3: "j. Polski",
    4: "j. Polski",
    5: "Matematyka",
    6: "Matematyka",
    7: "Grafika komputerowa",
    8: "Grafika komputerowa",
  },
  thursday: {
    1: "PAI",
    2: "PAI",
    3: "j. Polski",
    4: "j. Polski",
    5: "Matematyka",
    6: "Matematyka",
    7: "Grafika komputerowa",
    8: "Grafika komputerowa",
  },
  friday: {
    1: "PAI",
    2: "PAI",
    3: "j. Polski",
    4: "j. Polski",
    5: "Matematyka",
    6: "Matematyka",
    7: "Grafika komputerowa",
    8: "Grafika komputerowa",
  },
  saturday: {
    1: "",
    2: "",
    3: "",
    4: "",
    5: "",
    6: "",
    7: "",
    8: "",
  },
  sunday: {
    1: "",
    2: "",
    3: "",
    4: "",
    5: "",
    6: "",
    7: "",
    8: "",
  },
};

export default plan;
